---
- name: Cisco show version example
  hosts: testRouters
  gather_facts: false

  vars: # for execution environment
  
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:

  - name: Gather only the config and default facts
    ios_command:
      commands:
        sh ip inter br
    register: out

  - name: Show facts
    debug:
      msg: "{{ out.stdout_lines }}"
